DjangoUeditor/urls.py
#coding:utf-8
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import patterns, url
else:
    from django.conf.urls.defaults import patterns, url

from views import get_ueditor_controller

urlpatterns = patterns('',
    url(r'^controller/$',get_ueditor_controller)
)

blog/urls.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-
from django.conf.urls import patterns, url
from blog import views
from blog.feed import LatestBlogFeed


urlpatterns = patterns(
    '',
    url(r'^$', views.BlogIndex.as_view(), name='index'),
    url(r'^detail/(?P<blog_id>\d+)/$', views.BlogDetail.as_view(), name='detail'),
    url(r'^cate/(?P<cate_id>\d+)/$', views.BlogCate.as_view(), name='catelist'),
    url(r'^tag/(?P<tag_id>\d+)/$', views.BlogTag.as_view(), name='taglist'),
    url(r'^comment/', views.comment, name='comment'),
    url(r'^rss/$', LatestBlogFeed()),
)

cblog/urls.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url
import settings
from django.contrib import admin
from blog.sitemap import BlogSitemap
admin.autodiscover()
from blog.views import Home, About

sitemaps = {
    'blog': BlogSitemap
}

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'cblog.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^mcaptcha/', include('mcaptcha.urls', namespace='mcaptcha')),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^about/$', About.as_view(), name='about'),
    url(r'feedback/$', 'blog.views.feedback', name='feedback'),
    url(r'chat/', include('chat.urls', namespace='chat')),
    url(r'photo/', include('photo.urls', namespace='photo')),
    url(r'interest/', include('interest.urls', namespace='interest')),

    url(r'^sitemap\.xml/$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': {'blog':BlogSitemap,}}),

)
from django.conf import settings

if settings.DEBUG is False:
    urlpatterns += patterns('',
        #url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
         #   {'document_root': settings.MEDIA_ROOT}
       # ),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
   )

mcaptcha/urls.py
from django.conf.urls import patterns, url
import views

urlpatterns = patterns(
    '',
    url(r'^image/(?P<key>[\w\.]+)/$', views.mcaptcha, name='mcaptcha'),
    url(r'^refresh/$', views.mcaptcha_refresh, name='mcapt_refresh'),
)

photo/urls.py
from django.conf.urls import patterns, urlfrom photo import viewsurlpatterns = patterns(    '',    url(r'^$', views.photo, name='photo'),    url(r'^bing/$', views.bingindex, name='bingindex'),)

blog/forms.py
#-*- coding:utf-8 -*-
from django import forms
from models import FeedBackModel


class CommentForm(forms.Form):
    pre_comid = forms.IntegerField(required=False)
    anickname = forms.CharField(max_length=30, error_messages={'required': u'请填写昵称'})
    bemail = forms.EmailField(error_messages={'required': u'请填写您的邮箱(不会公开你的邮箱)', 'invalid': u'邮箱格有误,请重新输入'})
    cwebsite = forms.URLField(required=False, error_messages={'invalid': u'博客地址不正确(请以http或https开头)'})
    dcontent = forms.CharField(widget=forms.Textarea, error_messages={'required': u'你的评论在哪呢？'})
    mcaptcha = forms.CharField(max_length=8, required=False, error_messages={'required': u'请填写验证码', 'invalid': u'验证码不正确'})


class FeedBackForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(FeedBackForm, self).__init__(*args, **kwargs)
        self.fields['username'].error_messages = {'required': u'请填写昵称'}
        self.fields['useremail'].error_messages = {'required': u'请填写你的邮箱', 'invalid': u'邮箱格式错误,请重新输入'}
        self.fields['suggestion'].error_messages = {'required': u'你的反馈内容呢?'}

    class Meta:
        model = FeedBackModel
        fields = ['username', 'useremail', 'suggestion']
        widgets = {'suggestion': forms.Textarea}

blog/views.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-
from django.http.response import HttpResponse, Http404
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.utils import timezone
from blog.models import Blog, Category, Link, User, Comment, UserVisitFoot
from forms import CommentForm, FeedBackForm
from utils import get_user_ip
from django.views.generic.base import TemplateResponseMixin, View
import re
import random
import json


def save_user_visitfoot(request):
    ip = get_user_ip(request)
    print ip
    try:
        userfoot = UserVisitFoot.objects.get(userIP=ip)
    except:
        userfoot = UserVisitFoot(userIP=ip)

    userfoot.save()


def DeleteHeadBlank(s):
    for i in xrange(len(s)):
        if s[i] not in [' ', '   ']:
            return s[i:]


def ResponseMsg(status, errorMsg):
    reJson = {}
    reJson['status'] = status
    reJson['errorMsg'] = errorMsg
    return HttpResponse(json.dumps(reJson), content_type='application/json')


def comment(request):
    if request.is_ajax():
            form = CommentForm(request.POST)

            if form.is_valid():
                blog_id = request.GET.get('blog_id')
                blog = get_object_or_404(Blog, pk=blog_id)
                blog.comment_num += 1
                blog.save()
                # pre_comid = form.cleaned_data['pre_comid']
                nickname = form.cleaned_data['anickname']
                email = form.cleaned_data['bemail']
                website = form.cleaned_data['cwebsite']
                content = form.cleaned_data['dcontent']
                photo = str(random.randint(0, 9)) + '.png'
                u = User(name=nickname, email=email, website=website, photo=photo)
                u.save()
                c = Comment(user=u, blog=blog, content=content, comment_time=timezone.now())
                c.save()
                # sendCommentReply(email)
                # SendEmail_Comment(nickname,None)
                return ResponseMsg(True, u'谢谢你的评论')
            else:
               return ResponseMsg(False, form.errors.popitem()[1])
    else:
        raise Http404


def feedback(request):
    if request.is_ajax():
            form = FeedBackForm(request.POST)
            if form.is_valid():
                feedback = form.save(commit=False)
                feedback.save()
                return ResponseMsg(True, u'感谢你的反馈建议.我会及时进行改进.')
            else:
               return ResponseMsg(False, form.errors.popitem()[1])
    else:
        raise Http404


user_device_re = re.compile(r'(mobile|iphone|android|iemobile)')


class BlogBase(TemplateResponseMixin, View):
    template_name = ''
    template_name_m = ''

    def get_user_device(self):
        # return 'MOBILE'
        device = self.request.session.get('USER_VIEW_DEVICE', 'UNKNOWN_VIEW_DEVICE')
        if device != 'UNKNOWN_VIEW_DEVICE':
            return device

        HTTP_USER_AGENT = self.request.META.get('HTTP_USER_AGENT', '').lower()
        user_device = user_device_re.findall(HTTP_USER_AGENT)
        if len(user_device) > 0:
            self.request.session['USER_VIEW_DEVICE'] = 'MOBILE'
            return 'MOBILE'

        self.request.session['USER_VIEW_DEVICE'] = 'PC'
        return 'PC'

    def get_template_names(self):
        if self.get_user_device() == 'MOBILE':
            return [self.template_name_m]
        else:
            return [self.template_name]

    def get_context_data(self, extra_context):
        context = {
            'newblogs': Blog.objects.all().order_by('-publish_time')[0:8],
            'categorys': Category.objects.all(),
            'reads': Blog.objects.filter(read_num__gt=0).order_by('-read_num')[0:8],
            'comments': Blog.objects.filter(comment_num__gt=0).order_by('-comment_num')[0:8],
            'links': Link.objects.all(),
        }
        context.update(extra_context)
        return context


class Home(BlogBase):
    template_name = 'blog/home.html'
    template_name_m = 'blog/mobile/home.mobile.html'

    def get_context_data(self, extra_context):
        context = super(Home, self).get_context_data(extra_context)
        return context

    def get(self, request):

        print 'BlogHome View'
        extra_context = {
        }
        return self.render_to_response(self.get_context_data(extra_context))


class BlogIndex(BlogBase):
    template_name = 'blog/blog.html'
    template_name_m = 'blog/mobile/blog.mobile.html'

    def get_context_data(self, extra_context):
        context = super(BlogIndex, self).get_context_data(extra_context)
        return context

    def get(self, request):
        print 'BlogIndex'
        blog_list = Blog.objects.all().order_by('-publish_time')
        paginator = Paginator(blog_list, 5)
        try:
            page = int(request.GET.get('page', '1'))
        except ValueError:
            page = 1

        try:
            blogs = paginator.page(page)
        except (EmptyPage, InvalidPage):
            blogs = paginator.page(paginator.num_pages)
        extra_context = {
            'SHOWSHORTBLOG': 'True',
            'blogs': blogs,
        }
        return self.render_to_response(self.get_context_data(extra_context))


class BlogDetail(BlogBase):
    template_name = 'blog/detail.html'
    template_name_m = 'blog/mobile/detail.mobile.html'

    def get_context_data(self, extra_context):
        context = super(BlogDetail, self).get_context_data(extra_context)
        return context

    def get(self, request, blog_id):
        print 'BlogDetail'
        blog = Blog.objects.get(id=blog_id)
        blog.read_num += 1
        blog.save()
        try:
            pre_blog = Blog.objects.filter(publish_time__lt=blog.publish_time).order_by('-publish_time')[0]
        except:
            pre_blog = None
        try:
            next_blog = Blog.objects.filter(publish_time__gt=blog.publish_time).order_by('publish_time')[0]
        except:
            next_blog = None
        extra_context = {
            'SHOWSHORTBLOG': 'False',
            'blog': blog,
            'form': CommentForm(),
            'comments': Comment.objects.filter(blog=blog),
            'pre_blog': pre_blog,
            'next_blog': next_blog,
        }
        return self.render_to_response(self.get_context_data(extra_context))


class BlogCate(BlogBase):
    template_name = 'blog/blog.html'
    template_name_m = 'blog/mobile/blog.mobile.html'

    def get_context_data(self, extra_context):
        context = super(BlogCate, self).get_context_data(extra_context)
        return context

    def get(self, request, cate_id):
        print 'BlogCate'
        blog_list = Blog.objects.filter(category=cate_id)
        paginator = Paginator(blog_list, 5)
        try:
            page = int(request.GET.get('page', '1'))
        except ValueError:
            page = 1
        try:
            blogs = paginator.page(page)
        except (EmptyPage, InvalidPage):
            blogs = paginator.page(paginator.num_pages)
        extra_context = {
            'SHOWSHORTBLOG': 'True',
            'blogs': blogs,
        }
        return self.render_to_response(self.get_context_data(extra_context))


class BlogTag(BlogBase):
    template_name = 'blog/blog.html'
    template_name_m = 'blog/mobile/blog.mobile.html'

    def get_context_data(self, extra_context):
        context = super(BlogTag, self).get_context_data(extra_context)
        return context

    def get(self, request, tag_id):
        print 'BlogCate'
        blog_list = Blog.objects.filter(tags=tag_id)
        paginator = Paginator(blog_list, 5)
        try:
            page = int(request.GET.get('page', '1'))
        except ValueError:
            page = 1
        try:
            blogs = paginator.page(page)
        except (EmptyPage, InvalidPage):
            blogs = paginator.page(paginator.num_pages)
        extra_context = {
            'SHOWSHORTBLOG': 'True',
            'blogs': blogs,
        }
        return self.render_to_response(self.get_context_data(extra_context))


class About(BlogBase):
    template_name = 'blog/about.html'
    template_name_m = 'blog/mobile/about.mobile.html'

    def get_context_data(self, extra_context):
        context = super(About, self).get_context_data(extra_context)
        return context

    def get(self, request):
        print 'About'
        extra_context = {
            'form': FeedBackForm(),
        }
        return self.render_to_response(self.get_context_data(extra_context))

templates/blog/article.html
{% load filters %}
<table class="article_header theme_bd_Color"  border="0" cellpadding="0" cellspacing="0"style="table-layout: fixed;width: 100%;">
    <tbody>
        <tr class="article_header">
            <td class="article_info theme_bd_Color">
                <!-- Blog标题 -->
                <p class="title">
                    <a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a>
                </p>
                <!-- 标签 -->
                <div class="tag">
                    <span>
                        <a href="{% url 'blog:catelist' blog.category.id %}">{{ blog.category }}</a>
                        <i></i>
                        {% for tag in blog.tags.all %}
                            <a href="{% url 'blog:taglist' tag.id %}">{{ tag.tag_name }}</a>
                        {% endfor %}
                    </span>
                </div>
            </td>
            <td class="article_time theme_bk_Color">
                <span class="time_day">{{ blog.publish_time|date:"d" }}</span>
                <span class="time_month">{{ blog.publish_time|date:"M" }}</span>
                <span class="time_year">{{ blog.publish_time|date:"Y" }}</span>
            </td>
        </tr>
    </tbody>
</table>
<div class="article_body"style="clear:both;">
    {% if SHOWSHORTBLOG %}
        {{ blog.content|shortblog }}
    {% else %}
        {{ blog.content|safe }}
    {% endif %}
</div>

templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
    <meta name="author" content="d9chen">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale:1.2">
	<title>{% block title %}cheerfullchen{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static "blog/css/base.css" %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'blog/images/logo.png' %}">
    <script type="text/javascript"src="{% static 'site/jquery-1.8.2.min.js' %}"></script>
    {% block extra_meta %}
        <meta name="keywords" content="cheerfullchen d9chen cheer cheerfull 个人博客 Django">
    {% endblock %}
    {% block extra_link %}{% endblock %}
    {% block extra_js %}{% endblock %}
</head>
<body>
	<!-- 页面头部Begin -->
	<div class="header theme_bk_Color">
		<div class="header_main">
            <div class="logo">
                <a class="logoindex" href="/">
                    <img src="{% static 'blog/images/logo-2.png' %}"/>
                </a>
            </div>
			<div class="right_nav">
				<a class="{% block nav_index %}{% endblock %}" href="/">首页</a>
				<a class="{% block nav_blog %}{% endblock %}" href="{% url 'blog:index' %}">博客</a>
				<a class="{% block nav_photo %}{% endblock %}" href="{% url 'photo:photo' %}">图库</a>
				<a class="{% block nav_about %}{% endblock %}" href="/about">关于</a>
			</div>
		</div>
	</div>
	<!-- 页面头部End -->
    {% block container %}
    {% endblock %}
    <div class="filter"></div>
    <div class="error">
        <div class="error-title"></div>
        <p class="error-body"></p>
        <button id="id_error_ok">确定</button>
    </div>
	<!-- 页脚footerBegin -->
	<div class="footer theme_bk_Color">
		<div class="footer_main">
			<div class="f_left_copyright">
				<span>
					Desigend by <b>cheer</b>| Copyright 2014
				</span>
			</div>
			<div class="f_right_nav">
				<a href="/"class="backgound-color:#1D8DCD;">返回首页</a>
				<a href="/about">关于作者</a>
				<a href="/admin">管理登录</a>
			</div>
		</div>
	</div>
	<!-- 页脚footerEnd -->
</body>
</html>

templates/blog/blog.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block title %}Blog-Chen{% endblock %}
{% block extra_meta %}
	{{ block.super }}
	<meta name="description" content="{% for blog in blogs %} {{ blog.title }} {% endfor %}">
{% endblock %}
{% block extra_link %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/blog.css' %}">
	<link href="{% static 'syntaxhighlighter/css/shCore.css' %}" type="text/css" rel="stylesheet">
	<link href="{% static 'syntaxhighlighter/css/shThemeDefault.css' %}" type="text/css" rel="stylesheet">
{% endblock %}
{% block extra_js %}
<script src="{% static 'site/jquery-1.8.2.min.js' %}"></script>
	<script src="{% static 'syntaxhighlighter/js/XRegExp.js' %}" type="text/javascript"></script>
	<script src="{% static 'syntaxhighlighter/js/shCore.js' %}" type="text/javascript"></script>
	<script src="{% static 'syntaxhighlighter/js/shAutoloader.js' %}" type="text/javascript"></script>
	<script src="{% static 'site/syntaxhighlighter_autoloads.js' %}" type="text/javascript"></script>
{% endblock %}
{% block nav_blog %}focus{% endblock %}
{% block container %}
    <div class="container">
        {% include 'blog/side.html' %}
        <div class="right_article">
            {% for blog in blogs %}
                <!-- 博客正文 -->
                <div class="article theme_bd_Color theme_pb_Color">
                    {% include 'blog/article.html' %}
                    <!-- 文章浏览信息部分 -->
                    <div class="article_footer"style="float:right;padding-bottom:6px;margin-right:6px;">
                        <a href="{% url 'blog:detail' blog.id %}#comment">评论<span>[{{ blog.comment_num }}]</span></a>
                        <a href="{% url 'blog:detail' blog.id %}">阅读全文<span>[{{ blog.read_num }}]</span></a>
                    </div>
                </div>
            {% endfor %}
            <!-- 页码Begin -->
            {% if not blogs %}
                <p style="text-align:center;color:red;">啊哦!没有相关的内容哟,请尝试其他的吧.</p>
            {% else %}
			<div class="pagination theme_bd_Color">
                {% if blogs.has_previous %}
                    <a class="pageItem"style="float:left;" href="?page={{ 1 }}">首页</a>
				    <a class="pageItem"style="float:left;" href="?page={{ blogs.previous_page_number }}">上一页</a>
                {% endif %}
                <a class="pageItem on" {% if not blogs.has_next %}style="float:right;"{% endif %}>第{{ blogs.number }}页</a>
                {% if blogs.has_next %}
                    <a class="pageItem"style="float:right;" href="?page={{ blogs.paginator.num_pages }}">尾页</a>
				    <a class="pageItem"style="float:right;" href="?page={{ blogs.next_page_number }}">下一页</a>
                {% endif %}

			</div>
            {% endif %}
			<!-- 页码End -->
        </div>
    </div>

{% endblock %}

templates/blog/comlist.html
{% load filters %}
{% load staticfiles %}
<li class="one_comment">
    <a class="com_head_img" href="javascript:void(0);"><img src="{% static 'blog/images/headimg/'%}{{ comment.user.photo }}"></a>
    <div class="one_com_body">
        <div class="one_com_title">
            <a class="com_user"target="_blank" {% if comment.user.website %}href="{{ comment.user.website }}"{% endif %}>{{ comment.user.name }}</a>
            <span class="com_time">{{ comment.comment_time|formattime }}</span>
        </div>
        <div class="one_com_content">
            <p>{{ comment.content }}</p>
        </div>
    </div>
    <ul>

    </ul>
</li>

templates/blog/comment.html
{% load widget_tweaks %}
{#<!-- 评论Begin -->#}
{#<div id="comment">#}
{#    <h4>发表评论</h4>#}
{#    <form id="id_comment_form" method="post" action="{% url 'blog:comment' %}?blog_id={{ blog.id }}">#}
{#        {% csrf_token %}#}
{#        <div style="float:left;width:296px;">#}
{#            <div class="ynickname">#}
{#                <input id="id_user_nickname" type="text" placeholder="你的昵称" name="user_nickname">#}
{#            </div>#}
{#            <div class="ymail">#}
{#                <input id="id_user_email" type="email" placeholder="你的邮箱" name="user_email">#}
{#            </div>#}
{#            <div class="yblog">#}
{#                <input id="id_user_blog" type="text" placeholder="你的博客网址" name="user_blogurl">#}
{#            </div>#}
{#        </div>#}
{##}
{#        <div class="ycomment" style="float:left;width:700px;">#}
{#            <textarea id="id_user_comment" placeholder="你的留言" name="user_comment"></textarea>#}
{#            <div style="float:left;margin-top: 13px;width:100%;">#}
{#                <input id="id_user_idcode"type="text" placeholder="亲输入验证码" name="user_idcode" style="width:100px;float:left;">#}
{#                <a id="id_idcode" href=""title="点击更换验证码"><img src="./blog/images/code.png"/></a>#}
{#                <span id="id_error"></span>#}
{#                <button id="id_comment_submit"class="btn"style="float:right;padding:12px;"type="submit">发表评论</button>#}
{#            </div>#}
{#        </div>#}
{#    </form>#}
{#</div>#}
{#<!-- 评论End -->#}

<!-- 评论Begin -->
<div id="comment" class="theme_pb_Color">
    <h4>发表评论</h4>
    <form action="{% url 'blog:comment' %}?blog_id={{ blog.id }}" id="id_comment_form" method="post" >
        {% csrf_token %}
        {{ form.pre_comid|attr:"type:hidden" }}
        <div style="float:left;width:296px;">
            <div class="ynickname">
                {{ form.anickname|attr:"id:id_user_nickname"|attr:"placeholder:你的昵称" }}
            </div>
            <div class="ymail">
                {{ form.bemail|attr:"id:id_user_email"|attr:"placeholder:你的邮箱" }}
            </div>
            <div class="yblog">
                {{ form.cwebsite|attr:"id:id_user_blog"|attr:"placeholder:你的博客网址" }}
            </div>
        </div>

        <div class="ycomment" style="float:left;width:700px;">
            {{ form.dcontent|attr:"id:id_user_comment"|attr:"placeholder:你的评论" }}
            <div style="float:left;margin-top: 13px;width:100%;">
                {{ form.mcaptcha|attr:"id:id_user_idcode"|attr:"placeholder:亲输入验证码"|attr:"style:width:100px;float:left;" }}
                <a id="id_idcode" href="#refresh"title="点击更换验证码"><img src="{% url 'mcaptcha:mcaptcha' 0%}"/></a>
                <span id="id_error"></span>
                <button id="id_comment_submit"class="btn"style="float:right;padding:12px;"type="submit">提交评论</button>
            </div>
        </div>
    </form>
</div>

<!-- 评论End -->

templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block title %}{{ blog.title }}-Chen{% endblock %}
{% block extra_meta %}
	{{ block.super }}
	<meta name="description" content="{{ blog.title }} {% for tag in blog.tags.all %} {{ tag.tag_name }} {% endfor %}">
{% endblock %}
{% block extra_link %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/detail.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/blog.css' %}">
	<link href="{% static 'syntaxhighlighter/css/shCore.css' %}" type="text/css" rel="stylesheet">
	<link href="{% static 'syntaxhighlighter/css/shThemeDefault.css' %}" type="text/css" rel="stylesheet">
{% endblock %}
{% block extra_js %}
    <script src="{% static 'site/jquery-1.8.2.min.js' %}"></script>
{#	<script src="{% static 'site/placeholder.js' %}"></script>#}
	<script src="{% static 'syntaxhighlighter/js/XRegExp.js' %}" type="text/javascript"></script>
	<script src="{% static 'syntaxhighlighter/js/shCore.js' %}" type="text/javascript"></script>
	<script src="{% static 'syntaxhighlighter/js/shAutoloader.js' %}" type="text/javascript"></script>
	<script src="{% static 'site/syntaxhighlighter_autoloads.js' %}" type="text/javascript"></script>
    <script src="{% static 'blog/js/comment.js' %}" type="text/javascript"></script>
	<script>
{#		$(document).ready(function(){#}
{#			$.fn.placeholder();#}
{#		})#}
	</script>
{% endblock %}
{% block nav_blog %}focus{% endblock %}
{% block container %}
    <div class="container">
        <div style="margin-bottom: 24px;" class="theme_pb_Color">
            <!-- 博客正文 -->
            <div class="article theme_bd_Color">
                {% include 'blog/article.html' %}
                <!-- 文章浏览信息部分 -->
                <div class="article_footer"style="float:right;padding-bottom:6px;margin-right:6px;">
                    <span style="font-size:14px;color:#5E5E5E;">评论[{{ blog.comment_num }}]</span>
                    <span style="font-size:14px;color:#5E5E5E;">阅读[{{ blog.read_num }}]</span>
                </div>
            </div>
            <!-- 文章导航 -->
			<ul class="article_next_prev">
                {% if pre_blog %}
				    <li>上一篇：<a href="{% url 'blog:detail' pre_blog.id %}">{{ pre_blog.title }}</a></li>
                {% endif %}
                {% if next_blog %}
				<li>下一篇：<a href="{% url 'blog:detail' next_blog.id %}">{{ next_blog.title }}</a></li>
                {% endif %}
			</ul>
        </div>
{#        评论列表#}

            <!-- 评论列表Begin -->
            <div id="comment_list" class="comment_list theme_pb_Color">
                {% if comments %}<h4>所有评论</h4>{% endif %}
                <ul class="com_list">
                    {% for comment in comments %}
                        {% include 'blog/comlist.html' %}
                    {% endfor %}
                </ul>
            </div>
            <!-- 评论列表End -->
        {#评论#}
        {% include 'blog/comment.html' %}
    </div>

{% endblock %}

templates/blog/side.html
{% load filters %}
<div class="left_list">

{% if newblogs %}
<div class="list theme_pb_Color">
    <h4 class="theme_bk_Color">最新文章</h4>
    <ul>
        {% for nblog in newblogs %}
        <li>
            <a class="ta-c"href="{% url 'blog:detail' nblog.id %}">{{ nblog.title }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}

{% if categorys %}
<div class="list theme_pb_Color">
    <h4 class="theme_bk_Color">文章分类</h4>
    <ul>
        {% for cate in categorys %}
        <li>
            <a class="ta-c"href="{% url 'blog:catelist' cate.id %}">{{ cate.category_name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}

{% if reads %}
<div class="list theme_pb_Color">
    <h4 class="theme_bk_Color">阅读排行</h4>
    <ul>
        {% for read in reads %}
        <li>
            <a class="ta-c"href="{% url 'blog:detail' read.id %}">{{ read.title }}<span>[{{ read.read_num }}]</span></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}

{% if comments %}
<div class="list theme_pb_Color">
    <h4 class="theme_bk_Color">热门评论</h4>
    <ul>
        {% for comment in comments %}
        <li>
            <a class="ta-c"href="{% url 'blog:detail' comment.id %}#comment_list">{{ comment.title  }}<span>[{{ comment.comment_num }}]</span></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}

{% if links %}
<div class="list theme_pb_Color">
    <h4 class="theme_bk_Color">友情链接</h4>
    <ul>
        {% for link in links %}
        <li>
            <a href="{{ link.site_url }}"class="ta-c">{{ link.site_name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}
<div class="list rss">
    <a href="/blog/rss/">订阅我的博客(RSS)</a>
</div>
</div>